### ISSUE TITLE
BGP route reflectors managed in controller

### ISSUE THREAD

**Issue by foobarfran** [projectcalico/kube-controllers#482] opened 2020-05-11 19:29 UTC
It would be nice if we could automate bgp route reflectors configuration.

## Expected Behavior
Configure automatically certain calico-node pods as route reflectors.

## Current Behavior
A normal scenario is having dedicated calico-node pods to act as route reflectors in certain nodes (maybe masters or some kind of dedicates group of nodes). Every time we rotate a node in that group, we need to manually configure the new pod as a rr.

## Possible Solution
Maybe we could use an existent/new controller that configure calico pods that belong to nodes with certain labels (maybe a `BGP_RR_NODE_LABELS` env variable) as rr

**Comment by caseydavenport** [comment] 2020-05-13 19:28
Closing as a duplicate of https://github.com/projectcalico/calico/issues/2382

**Closed by caseydavenport** 2020-05-13 19:28 UTC
