### ISSUE TITLE
Memory leak in calico-kube-controllers leads to eviction

### ISSUE THREAD

**Issue by mcginne** [projectcalico/kube-controllers#375] opened 2019-05-13 13:46 UTC
## Expected Behavior
If the number of pods/services in a cluster remains fairly constant I would expect the memory used by calico-kube-controllers to remain fairly constant

## Current Behavior
We have seen calico-kube-controllers pods getting Evicted:

```
$ kubectl get pods -n kube-system -o=wide | grep calico-kube-controllers
calico-kube-controllers-77b7c75455-2vh27   1/1       Running   0          1d        10.184.152.189   10.184.152.189
calico-kube-controllers-77b7c75455-km9ls   0/1       Evicted   0          52d       <none>           10.184.152.150
calico-kube-controllers-77b7c75455-wdrlm   0/1       Evicted   0          39d       <none>           10.94.113.88
```
On the node where it was Evicted I see the following messages in kubelet.log:

```
May  1 21:00:28 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: W0501 21:00:28.176199  111916 eviction_manager.go:344] eviction manager: attempting to reclaim memory
May  1 21:00:28 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: I0501 21:00:28.176266  111916 eviction_manager.go:358] eviction manager: must evict pod(s) to reclaim memory
May  1 21:00:28 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: I0501 21:00:28.176362  111916 eviction_manager.go:376] eviction manager: pods ranked for eviction: calico-kube-controllers-77b7c75455-wdrlm_kube-system(b3c15
bf1-4ee0-11e9-92fc-062f94faef5c), calico-node-2hksk_kube-system(da17621d-5c94-11e9-af89-062f94faef5c), etcd-backup-operator-558d86c8cb-qln9x_armada(d85138eb-50b8-11e9-92fc-062f94faef5c), armada-ops-node-exporter-gnx7s_monitoring(63bc485b-60fa-11e9
-a5e7-069ee410d817), carrier-worker-verification-mc692_armada(dc8ea1da-5b7a-11e9-85ff-06724f530a1e), ibm-pause-ds-zmxgr_kube-system(cb30d7b3-4cc5-11e9-92fc-062f94faef5c), ibm-kube-fluentd-7p7d9_kube-system(f9685a6f-5f97-11e9-a34a-06724f530a1e), ar
mada-log-collector-ds-7dh8j_armada(02cd33da-65b6-11e9-af89-062f94faef5c)
May  1 21:00:28 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: I0501 21:00:28.176533  111916 kuberuntime_container.go:547] Killing container "docker://0e7a31e819299cfe88575a70f30280619d76f03a08083c4d8b90630e4288d7f7" wit
h 30 second grace period
May  1 21:00:29 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: I0501 21:00:29.304882  111916 kubelet_pods.go:1113] Killing unwanted pod "calico-kube-controllers-77b7c75455-wdrlm"
May  1 21:00:29 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: I0501 21:00:29.309041  111916 kuberuntime_container.go:547] Killing container "docker://0e7a31e819299cfe88575a70f30280619d76f03a08083c4d8b90630e4288d7f7" wit
h 30 second grace period
May  1 21:00:32 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: E0501 21:00:32.490800  111916 kuberuntime_container.go:65] Can't make a ref to pod "calico-kube-controllers-77b7c75455-wdrlm_kube-system(b3c15bf1-4ee0-11e9-9
2fc-062f94faef5c)", container calico-kube-controllers: selfLink was empty, can't make reference
May  1 21:00:32 stage-dal10-carrier5-worker-9002.alchemy.ibm.com kubelet.service[111916]: I0501 21:00:32.738932  111916 eviction_manager.go:158] eviction manager: pods calico-kube-controllers-77b7c75455-wdrlm_kube-system(b3c15bf1-4ee0-11e9-92fc-06
2f94faef5c) evicted, waiting for pod to be cleaned up
```

On the node where it was killed we can see a slow decline of memory available, then a large jump in memory available when it was killed:
<img width="1594" alt="42ce1b80-6d91-11e9-8695-bc6e886fd78d" src="https://user-images.githubusercontent.com/27362732/57624257-7b3bd980-7589-11e9-86e7-cf76ae0d7449.png">

The pod that is running now has been running for 3 days and is using 20GB - which seems excessive.

We are continually adding/deleting deployments and services on this cluster - but the total number of both remains fairly constant.

## Steps to Reproduce (for bugs)
Not sure exactly what causes this to occur - but we are running Kube v1.12 with `kube-controllers:v3.3.6`. We are continually adding/deleting new deployments/services - but not sure exactly what causes it.

## Context
We see the pod getting evicted regularly - we could set memory limit too, but it would be good to not have it growing in memory at all.

## Your Environment

* Kubernetes version (`kubectl version`): `v1.12.8+IKS`
* Manifest file used to deploy k8s policy:
* Operating System and version: `Ubuntu 18.04, kernel: 4.15.0-43-generic`
* Link to your project (optional):

Logs show lots of messages like this every 5 mins:
```
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-01.etcd-operator" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-15.etcd-operator" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-cit.default" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-01.default" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-14.default" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-11.etcd-operator" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.monitoring.default" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-03.etcd-operator" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.armada.armada-health" type="ServiceAccount"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-deployer.default" type="ServiceAccount"
2019-05-09 18:31:09.792 [INFO][1] serviceaaccount_controller.go 218: Create/Update ServiceAccount Profile in Calico datastore key="ksa.kubx-etcd-01.etcd-operator"
2019-05-09 18:31:09.792 [WARNING][1] cache.go 287: Value for key has changed, queueing update to reprogram key="ksa.kubx-etcd-07.etcd-operator" type="ServiceAccount"
...
...
2019-05-09 18:31:09.809 [INFO][1] serviceaaccount_controller.go 241: Update ServiceAccount Profile in Calico datastore with resource version 642840405 key="ksa.kubx-etcd-01.etcd-operator"
2019-05-09 18:31:09.825 [INFO][1] serviceaaccount_controller.go 247: Successfully updated profile key="ksa.kubx-etcd-01.etcd-operator"
2019-05-09 18:31:09.825 [INFO][1] serviceaaccount_controller.go 218: Create/Update ServiceAccount Profile in Calico datastore key="ksa.kubx-etcd-15.etcd-operator"
2019-05-09 18:31:09.834 [INFO][1] serviceaaccount_controller.go 241: Update ServiceAccount Profile in Calico datastore with resource version 642840580 key="ksa.kubx-etcd-15.etcd-operator"
2019-05-09 18:31:09.841 [INFO][1] serviceaaccount_controller.go 247: Successfully updated profile key="ksa.kubx-etcd-15.etcd-operator"
2019-05-09 18:31:09.841 [INFO][1] serviceaaccount_controller.go 218: Create/Update ServiceAccount Profile in Calico datastore key="ksa.kubx-cit.default"
2019-05-09 18:31:09.860 [INFO][1] serviceaaccount_controller.go 241: Update ServiceAccount Profile in Calico datastore with resource version 642840198 key="ksa.kubx-cit.default"
2019-05-09 18:31:09.875 [INFO][1] serviceaaccount_controller.go 247: Successfully updated profile key="ksa.kubx-cit.default"
2019-05-09 18:31:09.875 [INFO][1] serviceaaccount_controller.go 218: Create/Update ServiceAccount Profile in Calico datastore key="ksa.kubx-etcd-01.default"
2019-05-09 18:31:09.884 [INFO][1] serviceaaccount_controller.go 241: Update ServiceAccount Profile in Calico datastore with resource version 642840673 key="ksa.kubx-etcd-01.default"
2019-05-09 18:31:09.893 [INFO][1] serviceaaccount_controller.go 247: Successfully updated profile key="ksa.kubx-etcd-01.default"
2019-05-09 18:31:09.893 [INFO][1] serviceaaccount_controller.go 218: Create/Update ServiceAccount Profile in Calico datastore key="ksa.kubx-etcd-14.default"
...
...
```

**Comment by caseydavenport** [comment] 2019-05-15 23:13
@mcginne thanks for raising - this looks like a real bug.

**Comment by caseydavenport** [comment] 2019-08-22 22:14
We've fixed the issue causing the repeated log lines in the upcoming v3.9 release.

Once out, it would be good to see if this issue still exists.

**Comment by tmjd** [comment] 2019-09-24 15:02
@mcginne v3.9 has been released, please try this latest version and see if the problem is still present. Thanks.

**Comment by tmjd** [comment] 2019-11-27 22:08
Closing this for now. Please report back if you are still seeing this and we can re-open it. Thanks.

**Closed by tmjd** 2019-11-27 22:08 UTC
Labels: kind/bug, priority/P1
